config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#index'
  resources :countries, only: [:index, :show]
  resources :api, only: [:index, :show]
  post 'countries', to: 'countries#search'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < OpenStruct
end

app/models/country_data.rb
class CountryData < OpenStruct
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  def index
    @countries = WorldbankApi.countries()

    api_render @countries
  end

  def show
    country_code = params[:id]
    country = WorldbankApi.get_country(country_code)
    year = params[:year]
    from_year = params[:from_year]
    to_year = params[:to_year]
    range =
      if from_year and to_year
        (from_year.to_i .. to_year.to_i)
      elsif year
        y = year.to_i
        (y .. y)
      else
        y = WorldbankApi.current_year
        (y-20..y)
      end
    @data = WorldbankApi.country_data(country, range)

    api_render @data
  end

  private
  
  def api_render(table)
    case params[:format]
    when "json"
      render json: table
    when "xml"
      render xml: table
    else
      render json: table
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def index
    @interesting_countries = ["1W","XD","XL","US","EU","CN"].map{ |code| WorldbankApi.get_country code }

  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def index
    @countries = WorldbankApi.countries().sort_by(&:name)
  end

  def show
    country_code = params[:id]
    country = WorldbankApi.get_country(country_code)
    year = WorldbankApi.current_year
    range = (year-20..year)
    @data = WorldbankApi.country_data(country, range)
  end

  def search
    searched_country = params[:country]
    @countries = WorldbankApi.countries().select{ |country|
      country.name.downcase.match? searched_country or country.code == searched_country
    }
    if @countries.empty?
      redirect_back(fallback_location: root_path, notice: "Found no results.")
    else
      render :index
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/application/index.html.erb
<h1 class="h1">CarbonApp</h1>

<button class="btn btn-primary">
    <%= link_to "View all countries", countries_path %>
</button>

<h2>Regions of interest</h2>
<% @interesting_countries.each do |country| %>
    <button class="btn btn-light">
        <%= link_to country.name, country_path(country.code) %>
    </button>
<% end %>

app/views/countries/index.html.erb
<h1> Countries of the world </h1>

<%= form_tag countries_path do %>
  <%= text_field_tag(:country, params[:country], placeholder: 'Country name', class: 'form-inline md-form form-sm mt-0') %>
  <%= submit_tag("Search", class: 'btn btn-primary') %>
<% end %>

<p>

<ul class="list-group">
    <% @countries.each do |country| %>
        <li class="list-group-item">
            <%= link_to "#{country.name}", country_path(country.code) %>
        </li>
    <% end %>
</ul>

app/views/countries/show.html.erb
<% if @data.empty? %>
    There is no data for this country.
<% else %>
    <h1><%= @data.first.country.name %></h1>

    <h2>Population</h2>
    <% populations = Hash.new %>
    <% @data.each{ |d| populations[d.year]=d.population } %>
    <%= line_chart populations %>

    <h2>Total CO2 emmissions</h2>
    <% co2s = Hash.new %>
    <% @data.each{ |d| co2s[d.year]=d.co2 } %>
    <%= line_chart co2s %>

    <h2>CO2 per capita</h2>
    <% co2s_per_capita = Hash.new %>
    <% @data.each{ |d| co2s_per_capita[d.year] =
        if (d.population==0 or d.co2.nil? or d.population.nil?) then
            nil 
        else
            d.co2/d.population
        end } %>
    <%= line_chart co2s_per_capita %>

    <table>
        <th>Population</th><th>CO2</th>
        <% @data.each do |d| %>
            <tr>
                <td><%= d.population %></td>
                <td><%= d.co2 %></td>
            </tr>
        <% end %>
    </table>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarbonApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Navigation bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'Home', root_path, { class: "nav-link" } %>
          </li>
          <li class="nav-item active">
            <%= link_to 'Countries', countries_path, { class: "nav-link" } %>
          </li>
        </ul>
      </div>
    </nav>
    <!-- Notices here -->
    <% if notice %>
      <div class="alert alert-primary" role="alert">
        <%= notice %>
      </div>
    <% end %>
    <!-- The page itself -->
    <%= yield %>
  </body>
</html>